
// This file has been generated by the GUI designer. Do not modify.
namespace DMXForGamers
{
	public partial class ManualEventsConsole
	{
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.Table _sceneConsoleTable;
		
		private global::Gtk.HSeparator hseparator1;
		
		private global::Gtk.Table _eventConsoleTable;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget DMXForGamers.ManualEventsConsole
			global::Stetic.BinContainer.Attach (this);
			this.Name = "DMXForGamers.ManualEventsConsole";
			// Container child DMXForGamers.ManualEventsConsole.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this._sceneConsoleTable = new global::Gtk.Table (((uint)(3)), ((uint)(3)), false);
			this._sceneConsoleTable.Name = "_sceneConsoleTable";
			this._sceneConsoleTable.RowSpacing = ((uint)(6));
			this._sceneConsoleTable.ColumnSpacing = ((uint)(6));
			this.vbox1.Add (this._sceneConsoleTable);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this._sceneConsoleTable]));
			w1.Position = 0;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.vbox1.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hseparator1]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this._eventConsoleTable = new global::Gtk.Table (((uint)(3)), ((uint)(3)), false);
			this._eventConsoleTable.Name = "_eventConsoleTable";
			this._eventConsoleTable.RowSpacing = ((uint)(6));
			this._eventConsoleTable.ColumnSpacing = ((uint)(6));
			this.vbox1.Add (this._eventConsoleTable);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this._eventConsoleTable]));
			w3.Position = 2;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		}
	}
}
