
// This file has been generated by the GUI designer. Do not modify.
namespace DMXForGamers
{
	public partial class ManualEventsConsole
	{
		private global::Gtk.Table _consoleTable;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget DMXForGamers.ManualEventsConsole
			global::Stetic.BinContainer.Attach (this);
			this.Name = "DMXForGamers.ManualEventsConsole";
			// Container child DMXForGamers.ManualEventsConsole.Gtk.Container+ContainerChild
			this._consoleTable = new global::Gtk.Table (((uint)(3)), ((uint)(3)), false);
			this._consoleTable.Name = "_consoleTable";
			this._consoleTable.RowSpacing = ((uint)(6));
			this._consoleTable.ColumnSpacing = ((uint)(6));
			this.Add (this._consoleTable);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
