
// This file has been generated by the GUI designer. Do not modify.
namespace DMXForGamers
{
	public partial class ManualConsole
	{
		private global::Gtk.ScrolledWindow scrolledwindow1;
		
		private global::Gtk.Table _consoleTable;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget DMXForGamers.ManualConsole
			global::Stetic.BinContainer.Attach (this);
			this.Name = "DMXForGamers.ManualConsole";
			// Container child DMXForGamers.ManualConsole.Gtk.Container+ContainerChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			global::Gtk.Viewport w1 = new global::Gtk.Viewport ();
			w1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this._consoleTable = new global::Gtk.Table (((uint)(3)), ((uint)(3)), false);
			this._consoleTable.Name = "_consoleTable";
			this._consoleTable.RowSpacing = ((uint)(6));
			this._consoleTable.ColumnSpacing = ((uint)(6));
			w1.Add (this._consoleTable);
			this.scrolledwindow1.Add (w1);
			this.Add (this.scrolledwindow1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		}
	}
}
