
// This file has been generated by the GUI designer. Do not modify.
namespace DMXForGamers
{
	public partial class EventEditView
	{
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.Entry _descriptionEntry;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TreeView _eventsList;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Button _addEventButton;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget DMXForGamers.EventEditView
			global::Stetic.BinContainer.Attach (this);
			this.Name = "DMXForGamers.EventEditView";
			// Container child DMXForGamers.EventEditView.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Description");
			this.hbox2.Add (this.label1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this._descriptionEntry = new global::Gtk.Entry ();
			this._descriptionEntry.CanFocus = true;
			this._descriptionEntry.Name = "_descriptionEntry";
			this._descriptionEntry.IsEditable = true;
			this._descriptionEntry.InvisibleChar = '●';
			this.hbox2.Add (this._descriptionEntry);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this._descriptionEntry]));
			w2.Position = 1;
			this.vbox2.Add (this.hbox2);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this._eventsList = new global::Gtk.TreeView ();
			this._eventsList.CanFocus = true;
			this._eventsList.Name = "_eventsList";
			this.GtkScrolledWindow.Add (this._eventsList);
			this.vbox2.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.GtkScrolledWindow]));
			w5.Position = 1;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this._addEventButton = new global::Gtk.Button ();
			this._addEventButton.CanFocus = true;
			this._addEventButton.Name = "_addEventButton";
			this._addEventButton.UseUnderline = true;
			this._addEventButton.Label = global::Mono.Unix.Catalog.GetString ("Add Event");
			global::Gtk.Image w6 = new global::Gtk.Image ();
			w6.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			this._addEventButton.Image = w6;
			this.hbox1.Add (this._addEventButton);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this._addEventButton]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this._addEventButton.Clicked += new global::System.EventHandler (this.OnAddEventButtonClicked);
		}
	}
}
